### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by durwin-hawaii** [byuh/Maps#1]
Can you please install a license for this repository

**Comment by coopmaster123** [comment]
there is a LICENSE.md that says it was based on the BSD-3 License.
I added the LICENSE file which is under GNU 3.

**Comment by durwin-hawaii** [comment]
The license I was referring to was the GitHub repository license, not the  project license.

**Comment by coopmaster123** [comment]
are you referring to public vs private repository ? I am not sure exactly what you are referring to.

**Comment by durwin-hawaii** [comment]
Before there was no license for the repository but now I see there is a

“GNU General Public License v3.0”

license now
